name: Build and Deploy - be-banner

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'Muxi-X/forum-fe'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: registry.cn-shenzhen.aliyuncs.com

      - name: Build and push image
        run: |
          chmod +x ./scripts/push.sh
          ./scripts/push.sh ${{ secrets.IMAGE_REPO }}
  deploy:
    if: github.repository == 'Muxi-X/forum-fe'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts
      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER }} << EOF
            cd ~/forum
            docker rm -f ${SERVICE_NAME}
            docker rmi -f ${{ secrets.IMAGE_REPO }}/${SERVICE_NAME}:latest
            docker compose up -d ${SERVICE_NAME}
          EOF
